import type {
  CompatibilityGroup,
  CompatibilityRecord,
  CompatibilityResult,
  CompatibilityType,
} from "./types.ts";

export const compatibilityTypeLabels: Record<CompatibilityType, string> = {
  consumable_device: "Расходник ↔ аппарат",
  accessory_device: "Аксессуар ↔ аппарат",
  sensor_monitor: "Датчик ↔ монитор",
  cable_equipment: "Кабель ↔ оборудование",
  software_equipment: "ПО ↔ оборудование",
  option_equipment: "Опция ↔ оборудование",
};

function validateEvidence(record: CompatibilityRecord) {
  const { evidence } = record;
  if (
    evidence.evidenceIds.length === 0 ||
    evidence.sourceUrls.length === 0 ||
    evidence.documentVersionIds.length === 0
  ) {
    throw new Error(
      `CompatibilityRecord ${record.compatibilityId} requires evidence ids, source urls and document version ids.`,
    );
  }
}

export function createCompatibilityRecord(
  record: CompatibilityRecord,
): CompatibilityRecord {
  validateEvidence(record);
  return record;
}

export function buildCompatibilityResult(input: {
  productSlug: string;
  records: CompatibilityRecord[];
}): CompatibilityResult {
  const records = input.records
    .filter(
      (record) =>
        record.productA.slug === input.productSlug ||
        record.productB.slug === input.productSlug,
    )
    .map(createCompatibilityRecord)
    .sort((left, right) => {
      const leftTitle =
        left.productA.slug === input.productSlug
          ? left.productB.title
          : left.productA.title;
      const rightTitle =
        right.productA.slug === input.productSlug
          ? right.productB.title
          : right.productA.title;
      return leftTitle.localeCompare(rightTitle, "ru-RU");
    });

  const groups = new Map<CompatibilityType, CompatibilityRecord[]>();
  for (const record of records) {
    groups.set(record.compatibilityType, [
      ...(groups.get(record.compatibilityType) ?? []),
      record,
    ]);
  }

  const resultGroups: CompatibilityGroup[] = [...groups.entries()].map(
    ([type, groupRecords]) => ({
      type,
      label: compatibilityTypeLabels[type],
      records: groupRecords,
    }),
  );

  return {
    productSlug: input.productSlug,
    totalRecords: records.length,
    groups: resultGroups,
    warnings: [
      "Compatibility Engine does not use Candidate Claims directly.",
      "Compatibility is not inferred by analogy and is not generated by LLM.",
    ],
  };
}

export function filterCompatibilityRecords(
  records: CompatibilityRecord[],
  filter: "all" | "confirmed" | "conditions" | "not_verified",
) {
  if (filter === "confirmed") {
    return records.filter((record) => record.status === "compatible");
  }
  if (filter === "conditions") {
    return records.filter(
      (record) => record.status === "compatible_with_conditions",
    );
  }
  if (filter === "not_verified") {
    return records.filter(
      (record) =>
        record.status === "not_verified" || record.status === "unknown",
    );
  }
  return records;
}
