import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migration="supabase/migrations/202607200005_catalog_admin_v1.sql";
test("Catalog Admin is service-only and keeps imported products unpublished",async()=>{const [source,productImport]=await Promise.all([readFile(migration,"utf8"),readFile("supabase/migrations/202607200004_product_import_v1.sql","utf8")]);assert.match(source,/catalog admin requires service role/g);assert.match(source,/revoke all on function cloud_api\.catalog_admin_patch_product\(uuid,jsonb,text\) from public,anon,authenticated/);assert.match(productImport,/products_import_never_published/);});
test("Catalog Admin PATCH has an explicit editable whitelist",async()=>{const source=await readFile(migration,"utf8");const whitelist=source.match(/allowed text\[\] := array\[([^;]+)\];/)?.[1]??"";for(const field of ["title","shortDescription","description","seoTitle","seoDescription","manufacturerId","categoryId","applicationAreaId"])assert.match(whitelist,new RegExp(`'${field}'`));for(const field of ["sourceUid","sourceChecksum","rawSnapshot","importBatchKey"])assert.doesNotMatch(whitelist,new RegExp(field));assert.match(source,/immutable or unsupported field/);});
test("save recalculates quality state without approval",async()=>{const source=await readFile(migration,"utf8");assert.match(source,/missing_registration = not exists/);assert.match(source,/missing_documents = not exists/);assert.match(source,/when cardinality\(reasons\)>0 then 'pending'/);assert.doesNotMatch(source,/review_state.{0,300}approved/);});
test("internal UI and APIs are gated and no-store",async()=>{const [access,shared,list,editor]=await Promise.all([readFile("lib/internal-access.ts","utf8"),readFile("app/api/internal/catalog-admin/_shared.ts","utf8"),readFile("components/internal/CatalogAdminList.tsx","utf8"),readFile("components/internal/CatalogAdminEditor.tsx","utf8")]);assert.match(access,/CYBERMEDICA_ENABLE_CATALOG_ADMIN/);assert.match(shared,/private, no-store/);assert.match(list,/Поиск по названию или slug/);assert.match(list,/missing_registration/);assert.match(editor,/Raw snapshot \(read-only\)/);assert.match(editor,/datalist/);});
test("API accepts only the eight editable fields",async()=>{const source=await readFile("app/api/internal/catalog-admin/products/[id]/route.ts","utf8");assert.match(source,/const editable = new Set/);assert.match(source,/Only editable catalog fields are accepted/);assert.doesNotMatch(source,/publicationStatus","published|sourceChecksum","sourceUid/);});
test("Catalog Admin scopes cloud_api headers to its server-only adapter",async()=>{const [adapter,client]=await Promise.all([readFile("lib/catalog-admin/server.ts","utf8"),readFile("lib/supabase/client.server.ts","utf8")]);assert.match(adapter,/import "server-only"/);assert.match(adapter,/"Accept-Profile": "cloud_api"/);assert.match(adapter,/"Content-Profile": "cloud_api"/);assert.doesNotMatch(client,/Accept-Profile|Content-Profile/);});
