"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import type { CatalogAdminPatch, CatalogAdminProduct, CatalogAdminReference } from "@/lib/catalog-admin";

type Refs={manufacturers:CatalogAdminReference[];categories:CatalogAdminReference[];applicationAreas:CatalogAdminReference[]};
export default function CatalogAdminEditor({initialProduct,references}:{initialProduct:CatalogAdminProduct;references:Refs}){
 const [product,setProduct]=useState(initialProduct);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 const [form,setForm]=useState<CatalogAdminPatch>({title:product.title,model:product.model,shortDescription:product.shortDescription,description:product.description,seoTitle:product.seoTitle,seoDescription:product.seoDescription,manufacturerId:product.manufacturerId,categoryId:product.categoryId,applicationAreaId:product.applicationAreaId});
 const set=<K extends keyof CatalogAdminPatch>(key:K,value:CatalogAdminPatch[K])=>setForm(current=>({...current,[key]:value}));
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage("");try{const response=await fetch(`/api/internal/catalog-admin/products/${product.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!response.ok)throw new Error("Сохранение не выполнено");const updated=await response.json() as CatalogAdminProduct;setProduct(updated);setMessage("Изменения сохранены, quality flags пересчитаны.");}catch(value){setMessage(value instanceof Error?value.message:"Ошибка сохранения");}finally{setSaving(false);}}
 const preview=useMemo(()=>`<!doctype html><meta charset="utf-8"><style>body{font:14px/1.55 system-ui;padding:12px;color:#334155}img{max-width:100%}</style>${form.description??""}`,[form.description]);
 return <form onSubmit={save} className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,.6fr)]"><div className="space-y-6">
  <Section title="Карточка товара"><div className="grid gap-4 md:grid-cols-2"><Field label="Название"><input required value={form.title??""} onChange={e=>set("title",e.target.value)} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2"/></Field><Field label="Модель"><input required value={form.model??""} onChange={e=>set("model",e.target.value)} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2"/></Field><Read label="Slug" value={product.slug}/><Read label="Source URL" value={product.sourceUrl??"—"}/><Field label="Краткое описание"><textarea value={form.shortDescription??""} onChange={e=>set("shortDescription",e.target.value)} className="mt-2 block min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2"/></Field></div><Field label="Описание"><textarea value={form.description??""} onChange={e=>set("description",e.target.value)} className="mt-2 block min-h-48 w-full rounded-lg border border-slate-300 px-3 py-2 font-mono text-sm"/></Field><div className="mt-4"><div className="mb-2 text-sm font-medium text-slate-700">HTML preview</div><iframe title="Предпросмотр HTML-описания" sandbox="" srcDoc={preview} className="h-56 w-full rounded-lg border border-slate-200 bg-white"/></div></Section>
  <Section title="Классификация"><div className="grid gap-4 md:grid-cols-3"><Reference label="Производитель" value={form.manufacturerId} items={references.manufacturers} onChange={v=>set("manufacturerId",v)}/><Reference label="Категория" value={form.categoryId} items={references.categories} onChange={v=>set("categoryId",v)}/><Reference label="Область применения" value={form.applicationAreaId} items={references.applicationAreas} onChange={v=>set("applicationAreaId",v)}/></div></Section>
  <Section title="SEO"><div className="grid gap-4 md:grid-cols-2"><Field label="SEO title"><input value={form.seoTitle??""} onChange={e=>set("seoTitle",e.target.value)} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2"/></Field><Field label="SEO description"><textarea value={form.seoDescription??""} onChange={e=>set("seoDescription",e.target.value)} className="mt-2 block min-h-24 w-full rounded-lg border border-slate-300 px-3 py-2"/></Field></div></Section>
  <Section title={`Характеристики (${product.characteristics.length})`}><div className="divide-y divide-slate-100">{product.characteristics.map((item,index)=><div key={`${item.name}-${index}`} className="grid grid-cols-2 gap-4 py-2 text-sm"><span className="text-slate-500">{item.name}</span><span>{item.value}{item.unit?` ${item.unit}`:""}</span></div>)}</div></Section>
  <Section title={`Галерея (${product.media.length})`}><div className="grid gap-3 sm:grid-cols-3">{product.media.map(item=><a key={item.url} href={item.url} target="_blank" rel="noreferrer" className="truncate rounded-lg border border-slate-200 p-3 text-sm text-teal-700">{item.role}: {item.url}</a>)}</div></Section>
 </div><aside className="space-y-6"><div className="sticky top-6 space-y-6"><Section title="Состояние"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Catalog Quality</span><strong>{product.catalogQualityStatus}</strong></div><div className="mt-2 flex items-center justify-between"><span className="text-sm text-slate-500">Review</span><strong>{product.reviewState}</strong></div><div className="mt-2 flex items-center justify-between"><span className="text-sm text-slate-500">Publication</span><strong>{product.publicationStatus}</strong></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(product.qualityFlags).filter(([,v])=>v).map(([key])=><span key={key} className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-800">{key}</span>)}</div>{product.warnings.map(w=><div key={`${w.code}-${w.message}`} className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><strong>{w.code}</strong><div>{w.message}</div></div>)}</Section>
 <Section title="Immutable source"><dl className="space-y-2 text-xs"><Read label="Source UID" value={product.immutable.sourceUid}/><Read label="Checksum" value={product.immutable.sourceChecksum}/><Read label="Schema" value={product.immutable.snapshotVersion}/><Read label="Batch" value={product.immutable.importBatchKey}/></dl><details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-teal-700">Raw snapshot (read-only)</summary><pre className="mt-3 max-h-96 overflow-auto rounded-lg bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(product.immutable.rawSnapshot,null,2)}</pre></details></Section>
 <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><button type="submit" disabled={saving} className="w-full rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white hover:bg-teal-800 disabled:opacity-50">{saving?"Сохранение…":"Сохранить"}</button><div aria-live="polite" className="mt-3 min-h-5 text-sm text-slate-600">{message}</div><Link href="/internal/catalog-admin" className="mt-3 block text-center text-sm text-teal-700">← Вернуться к списку</Link></div></div></aside></form>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-semibold text-slate-950">{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-slate-700">{label}{children}</label>}
function Read({label,value}:{label:string;value:string}){return <div className="min-w-0"><dt className="text-slate-500">{label}</dt><dd className="break-all font-mono text-slate-800">{value}</dd></div>}
function Reference({label,value,items,onChange}:{label:string;value:string|null|undefined;items:CatalogAdminReference[];onChange:(value:string|null)=>void}){const listId=`reference-${label.toLowerCase().replaceAll(" ","-")}`;const selected=items.find(item=>item.id===value)?.name??"";return <label className="text-sm font-medium text-slate-700">{label}<input list={listId} defaultValue={selected} onChange={event=>onChange(items.find(item=>item.name===event.target.value)?.id??null)} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Начните вводить название"/><datalist id={listId}>{items.map(item=><option key={item.id} value={item.name}/>)}</datalist></label>}
